### ISSUE TITLE
`UNDEFINED-ALIEN-VARIABLE-ERROR` on x86-64 windows

### ISSUE THREAD

**Issue by kilimanjaro** [quil-lang/sbcl-librarian#1]
I tried this out using Windows 10 via Parallels for macOS. I'm using msys2, with gcc 11.2.0 from the latest mingw-w64. 

I built SBCL from source (commit `02635ecb29aed48e2f97cae25817b51656224f36`) with no apparent problems. I also built `libsbcl.so`, just via the ordinary `make-shared-library.sh`.

Using `sbcl-librarian`, I'm able to produce `libcalc.core`. However, when I try the following example (not building another dll, but just linking against `libsbcl.so`) I get an error

`example.c`
```
#include "libcalc.h"
err_t (*calc_int_literal)(int value, expr_type *result);
err_t (*calc_int_literal_value)(expr_type expr, int *result);
err_t (*calc_int_literal_p)(expr_type obj, int *result);
err_t (*calc_sum_expression)(expr_type left, expr_type right, expr_type *result);
err_t (*calc_sum_expression_left_arg)(expr_type expr, expr_type *result);
err_t (*calc_sum_expression_right_arg)(expr_type expr, expr_type *result);
err_t (*calc_sum_expression_p)(expr_type expr, int *result);
err_t (*calc_simplify)(expr_type expr, expr_type *result);
err_t (*calc_parse)(char * source, expr_type *result);
err_t (*calc_expression_to_string)(expr_type expr, char * *result);
void (*release_handle)(void *handle);
int (*handle_eq)(void *a, void *b);
extern int initialize_lisp(int argc, char **argv);


int main(int argc, char** argv) {
  return initialize_lisp(argc, argv);
}
```
I compile with `cc example.c libsbcl.so`

I run with `./a.exe --core libcalc.core` and see the following
```
$ ./a.exe --core libcalc.core
This is SBCL 2.1.0, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
Unhandled SB-KERNEL::UNDEFINED-ALIEN-VARIABLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                                 {10029F0003}>:
  Attempt to access an undefined alien variable.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10029F0003}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-KERNEL::UNDEFINED-ALIEN-VARIABLE-ERROR {1002A05913}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SB-KERNEL::UNDEFINED-ALIEN-VARIABLE-ERROR {1002A05913}>)
2: (INVOKE-DEBUGGER #<SB-KERNEL::UNDEFINED-ALIEN-VARIABLE-ERROR {1002A05913}>)
3: (ERROR SB-KERNEL::UNDEFINED-ALIEN-VARIABLE-ERROR)
4: ("foreign function: #x7FF81914DC7A")
5: ("foreign function: #x7FF81914DD50")
6: ((SETF SB-SYS:SAP-REF-SAP) :INVALID-VALUE-FOR-UNESCAPED-REGISTER-STORAGE :INVALID-VALUE-FOR-UNESCAPED-REGISTER-STORAGE :INVALID-VALUE-FOR-UNESCAPED-REGISTER-STORAGE)
7: (SB-EVAL::EVAL-PROGN ((SETF (SB-SYS:SAP-REF-SAP SB-ALIEN::SAP (/ SB-ALIEN::OFFSET SB-VM:N-BYTE-BITS)) SB-ALIEN::VALUE) (SB-ALIEN-INTERNALS:NATURALIZE SB-ALIEN::VALUE (QUOTE #<SB-ALIEN-INTERNALS:ALIEN-POINTER-TYPE (* T)>))) #<SB-EVAL::ENV {1002A05083}>)
8: ((SETF SB-ALIEN-INTERNALS:%ALIEN-VALUE) #<SB-ALIEN-INTERNALS:ALIEN-VALUE :SAP #X20220B70 :TYPE (* T)> #.(SB-SYS:INT-SAP #X2019D380000) 0 #<SB-ALIEN-INTERNALS:ALIEN-POINTER-TYPE (* T)>)
9: (SB-IMPL::START-LISP)
10: ("foreign function: #x7FF81914DC7A")
11: ("foreign function: #x7FF81912445E")

unhandled condition in --disable-debugger mode, quitting
Missing required foreign symbol 'log1p'
<??? type 199>
```

I'm not sure what this `log1p` business is about, but I did notice that it's referenced here https://github.com/sbcl/sbcl/blob/d35ad6f9bee212499cb827fec3195bf2064c10a2/src/runtime/mswin64.def

**Comment by karlosz** [comment]
So this might be where something like `dllexport` is needed. Basically what SBCL is doing here is that it is trying to initialize the C symbols with the appropriate function pointers, but it is unable to find the symbols after loading the shared object which is supposed to allocate them, meaning that the shared object symbols aren't being exported properly.

Could you try adding `dllexport` or whatever is appropriate to the C files and then seeing if that fixes the issue? The symbols from libcalc.c need to be external such that the Windows equivalent of `dlsym` can find it so SBCL can initialize them.

**Comment by kilimanjaro** [comment]
I tried that, but to no avail.  My understanding of `__declspec(dllexport)` is that if you don't have any of these annotations, all non-static functions get exported. The reason for `__declspec(dllexport)` is to indicate that you only want a subset of these to actually get exported, and once the linker sees one of those, it changes behavior from "everything gets exported" to "only export things with the appropriate marks".  So for example

`example_all.c`
```
int foo() {
  return 0;
}

int bar() {
  return 0;
}
```
compiled with `cc -shared -o export_all.dll export_all.c`
I can look at the symbols using either `objdump` or msvc `dumpbin` or the mingw tool `gendef`
```
$ gendef - export_all.dll
;
; Definition file of export_all.dll
; Automatic generated by gendef
; written by Kai Tietz 2008
;
LIBRARY "export_all.dll"
EXPORTS
bar
foo
 * [export_all.dll] Found PE+ image
```

If instead I mark `foo` as `__declspec(dllexport)` then I get

```
$ gendef - export.dll
;
; Definition file of export.dll
; Automatic generated by gendef
; written by Kai Tietz 2008
;
LIBRARY "export.dll"
EXPORTS
foo
 * [export.dll] Found PE+ image
```

Anyways, I tried a few variants of this experiment with the earlier example. I still see the same behavior, even if I first compile a `libcalc.c` to a `libcalc.dll`, linking with `libsbcl.so`, and explictly marking everything to be exported. 

I still don't have an explanation for why `sbcl.exe` needs those extra definitions (e.g. https://github.com/sbcl/sbcl/blob/d35ad6f9bee212499cb827fec3195bf2064c10a2/src/runtime/mswin64.def and a similar file). If I look at the symbols of `sbcl.exe`, this time (for no good reason) using the msvc `dumpbin` tool, I get a very long list, with the `log1p` thing referenced above

`dumpbin /exports c:\Users\erik\source\sbcl\src\runtime\sbcl.exe`

```
...
        249   F8 000494D0 lisp_init_time
        250   F9 00049330 lisp_linkage_table_n_prelinked
        251   FA 00037540 lisp_register_names
        252   FB 00049260 lisp_sig_handlers
        253   FC 000494A0 lisp_startup_options
        254   FD 000179C0 lisp_symbol_from_tls_index
        255   FE 0001CB10 load_core_bytes
        256   FF 00003A10 load_core_file
        257  100 0002FFC0 log1p
        258  101 00002220 log_backtrace_from_fp
        259  102 00023BC0 log_generation_stats
        260  103 00019570 lookup_by_name
        261  104 00019600 lookup_by_obj
        262  105 0000A870 lose
...
```

However, `libsbcl.so` does not export so many things (including `log1p`), and this `log1p` is also not found in `msvcrt.dll` (which is a windows thing where the other C std library symbols seem to be coming from). I tried just defining my own (either adding to my dll or the example exe I produce), and I'm still getting this alien error. I also tried the suggestion made here, just with the dumb hope that it would work, but to no avail https://github.com/sbcl/sbcl/blob/d35ad6f9bee212499cb827fec3195bf2064c10a2/src/runtime/arm64-linux-os.c#L104

(Perhaps I'm barking up the wrong tree with this `log1p` business).

**Comment by kilimanjaro** [comment]
Just to follow up on our previous discussion, I got an example working with a slightly modified sbcl, which tries harder to emulate `dlsym` behavior on windows (looking for symbol names across all DLLs in the process)

```
diff --git a/src/code/win32-foreign-load.lisp b/src/code/win32-foreign-load.lisp
index 690fd1590..fdc9a351a 100644
--- a/src/code/win32-foreign-load.lisp
+++ b/src/code/win32-foreign-load.lisp
@@ -23,6 +23,15 @@
   (handle hinstance)
   (symbol c-string))
 
+(define-alien-routine ("GetCurrentProcess" getcurrentprocess) hinstance)
+
+;; for PSAPI_VERSION=2, we need K32EnumProcessModules
+(define-alien-routine ("K32EnumProcessModules" enumprocessmodules) (signed 32)
+  (process hinstance)
+  (modules (* hinstance))
+  (cb (signed 32))
+  (cb-needed (* (signed 32))))
+
 (define-alien-routine ("SetStdHandle" set-std-handle)
    void
  (id int)
@@ -86,11 +95,19 @@
   ;; Also, GetProcAddress doesn't call SetLastError(0) on success,
   ;; and GetLastError() doesn't either. For now, we assume that
   ;; GetProcAddress() won't return NULL on success.
-  (let* ((extern (coerce symbol 'base-string))
-         (result nil))
-    (dolist (handle
-              (cons *runtime-dlhandle*
-                    (mapcar #'shared-object-handle *shared-objects*)))
+  (let ((extern (coerce symbol 'base-string))
+        (result nil)
+        (loaded-modules
+          (with-alien ((modules (array hinstance 1024))
+                       (cb-needed (signed 32)))
+            (enumprocessmodules (getcurrentprocess)
+                                (cast modules (* hinstance))
+                                1024
+                                (addr cb-needed))
+            (loop :for i :below (floor cb-needed
+                                       (alien-size hinstance :bytes))
+                  :collect (deref modules i)))))
+    (dolist (handle (cons *runtime-dlhandle* loaded-modules))
       (when handle
         (setf result (sap-int (getprocaddress handle extern)))
         (when (not (zerop result))
```

**Comment by kilimanjaro** [comment]
Note that in the above, for `PSAPI_VERSION=1` we'd use `EnumProcessModules`. Not sure exactly when/where the switchover occurs.

**Comment by kilimanjaro** [comment]
Also, re the log1p business, I have tried making a shared library which basically exports a wrapper to `sb-kernel::%log1p`, and it worked just fine (despite still giving the message "Missing required foreign symbol 'log1p'"). Not sure what the deal with that is, but I'm not too worried.

**Comment by karlosz** [comment]
So we've determined one way to get around this on Windows is to simply bundle the produced shared library artifact with `libsbcl` itself, via static linking followed by producing a shared library again. This way, the runtime truly can look in its own module handler for the functionality we want.

**Comment by svetlyak40wt** [comment]
@karlosz could you please explain, how to use this workaround?

I'm trying to get [libcalc](https://github.com/quil-lang/sbcl-librarian/tree/main/examples/libcalc) example working on Windows but without any success :(

**Comment by stylewarning** [comment]
> @karlosz could you please explain, how to use this workaround?
> 
> 
> 
> I'm trying to get [libcalc](https://github.com/quil-lang/sbcl-librarian/tree/main/examples/libcalc) example working on Windows but without any success :( 

I'm happy if you make a new issue with this request, so that it can be tracked and documented appropriately.
