### ISSUE TITLE
Allow exporting Lisp functions under a custom name

### ISSUE THREAD

**Issue by kartik-s** [quil-lang/sbcl-librarian#13]
# Problem
I want to be able to export a Lisp function under a custom name.

As an example, Quilc defines the [compiler-hook](https://github.com/quil-lang/quilc/blob/49159dea612cd4f0000b868db04c546621102880/src/compilation-methods.lisp#L150) function in the `#:cl-quil` package. When building a shared library for `quilc`, I want to map this function to the C function `quilc_compile_quil`.

**Comment by karlosz** [comment]
Fixed in https://github.com/quil-lang/sbcl-librarian/commit/329d9dd15b3ebdb313664f607b05de58072c1e3c.

Use the syntax (ALIEN-NAME LISP-NAME) as is the convention for Lisp FFI.
