### ISSUE TITLE
find-package bug in example/libcalc.lisp

### ISSUE THREAD

**Issue by captnjameskirk** [quil-lang/sbcl-librarian#25]
Line 42 in the parse function:
```
(find-package "SBCL-LIBRARIAN-EXAMPLE")
```
The package name is actually `sbcl-librarian/example/libcalc`. It looks like the name was changed in [this](https://github.com/quil-lang/sbcl-librarian/commit/ddba2ae1ca95eb3c0b6587606de063d175d84b77#diff-8781310b2976c93332fd77612fb863a193e4a45a5ecfcc7d326a633023929540R1) commit but the line mentioned above wasn't updated to match.

P.S. The README note regarding `-pagezero_size` on OS X should probably mention that it applies to intel-based Macs. It's not needed (and doesn't work) on Apple Silicon.

**Comment by karlosz** [comment]
Fixed in https://github.com/quil-lang/sbcl-librarian/commit/6f82d28eee0e8e07e11403cd15ce40c801bf23d4.
